Translation
PearsonEducation/bag-of-holding pull request #15
Opened 2017-02-21 01:35 UTC by ribeiroit

Hi,

I've added the internacionalization support to all strings and already translated the messages to brazilian portuguese. I've been creating an automation to install boh using by puppet available here: https://github.com/ribeiroit/boh-puppet. 

The next steps are creating some functional tests to check translated messages and validate the interfaces.

If you have some considerations, please let me know. 

Thank you, very much.

2017-02-21 23:58 UTC, aparsons requested changes
Thank you for this pull request! I have looked through the changes fully and have a few minor suggestions. After a commit has been made which addresses the two points, I will be happy to merge your contributions. 

Obrigado!

2017-02-21 23:58 UTC, aparsons commented on project/boh/admin.py
>          ('Metadata', {
`_('Metadata')`

2017-02-21 23:58 UTC, aparsons commented on project/boh/admin.py
>          ('ThreadFix', {
`_('ThreadFix')`

2017-02-22 01:18 UTC, ribeiroit reviewed
Agreed!

2017-02-22 04:07 UTC, aparsons approved these changes

2017-02-22 04:08 UTC, merged